import 'package:flutter/material.dart';

class LocaleNotifier extends ValueNotifier<Locale> {
  LocaleNotifier(super.value);

  void setLocale(String languageCode) {
    value = Locale(languageCode);
    notifyListeners();
  }
}

class AppLocalizations {
  static final LocaleNotifier currentLocaleNotifier =
      LocaleNotifier(const Locale('en'));

  static Locale get currentLocale => currentLocaleNotifier.value;

  static void setLocale(String languageCode) {
    currentLocaleNotifier.setLocale(languageCode);
  }

  static String getLanguageName(String code) {
    switch (code) {
      case 'bn':
        return 'বাংলা';
      case 'ar':
        return 'العربية';
      case 'ur':
        return 'اردو';
      case 'en':
      default:
        return 'English';
    }
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_to': 'WELCOME TO',
      'ruqyah_healing': 'RUQYAH HEALING',
      'tagline': 'Compassionate care for body, mind and soul',
      'choose_language': 'Choose your language',
      'continue': 'Continue',
      'sign_in_account': 'SIGN IN TO YOUR ACCOUNT',
      'create_account_title': 'CREATE YOUR ACCOUNT',
      'email': 'Email',
      'phone': 'Phone',
      'email_address': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'send_otp': 'Send OTP',
      'otp_code': 'OTP Code',
      'select_role': 'Select Role',
      'user': 'User',
      'raki': 'Raki',
      'therapist': 'Therapist',
      'full_name': 'Full Name',
      'or_continue_with': 'or continue with',
      'continue_google': 'Continue with Google',
      'home': 'Home',
      'services': 'Services',
      'bookings': 'Bookings',
      'learn': 'Learn',
      'profile': 'Profile',
      'settings': 'Settings',
      'greeting': 'Assalamu Alaikum,',
      'health_index': 'Health Index',
      'holistic_services': 'Holistic Services',
      'prayer_times': "Today's Prayer Times",
      'my_appointments': 'My Appointments',
      'browse_category': 'Browse by Category',
      'featured_courses': 'Featured Courses',
      'personal_info': 'Personal Information',
      'logout': 'Logout',
      'theme_mode': 'Theme Mode',
      'language': 'Language',
      'good': 'Good',
      'overall_wellness': 'Overall physical & spiritual wellness',
      'next_appointment': 'NEXT APPOINTMENT',
      'ruqyah': 'Ruqyah',
      'hijama': 'Hijama',
      'acupuncture': 'Acupuncture',
      'emergency': 'Emergency',
      'preferences': 'PREFERENCES',
      'text_size': 'Text Size',
      'display': 'Display',
      'reduce_motion': 'Reduce Motion',
      'prayer_reminders': 'Prayer Reminders',
      'audio_downloads': 'Audio Downloads',
      'security_privacy': 'SECURITY & PRIVACY',
      'biometric_lock': 'Biometric Lock',
      'connected_devices': 'Connected Devices',
      'health_connect': 'Health Connect',
      'notification_settings': 'Notification Settings',
      'export_my_data': 'Export My Data',
      'delete_account': 'Delete Account',
      'about_legal': 'ABOUT & LEGAL',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'about_ruqyah': 'About Ruqyah Healing',
      'ai_symptom_guide': 'AI Symptom Guide',
      'ai_symptom_sub': 'Get instant Islamic guidance & duas',
      'ruqyah_title': 'RUQYAH',
      'ruqyah_sub': "Qur'anic healing for protection and relief from spiritual distress.",
      'hijama_title': 'HIJAMA',
      'hijama_sub': 'Cupping therapy for natural detoxification and physical restoration.',
      'acupuncture_title': 'ACUPUNCTURE',
      'acupuncture_sub': 'Holistic healing practices to maintain physical balance and energy wellness.',
      'courses': 'Courses',
      'learn_protection': 'Learn protection...',
      'store': 'Store',
      'natural_remedies': 'Natural remedies...',
      'patient_portal': 'PATIENT PORTAL',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'upcoming_sessions': 'UPCOMING SESSIONS',
      'rescheduling_info': 'Free rescheduling or cancellation is allowed up to 24 hours prior to the scheduled session.',
      'add_to_calendar': 'Add all upcoming to calendar',
      'book_new_appointment': 'Book a New Appointment',
      'learning': 'Learning',
      'learning_sub': 'Grow in knowledge, serve with sincerity.',
      'continue_learning': 'CONTINUE LEARNING',
      'view_all': 'View all',
      'sessions_completed': 'SESSIONS Completed',
      'health_index_label': 'HEALTH INDEX',
      'days_active': 'DAYS ACTIVE',
      'streak_tracker': 'Streak Tracker',
      'subscription_plans': 'Subscription Plans',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'privacy_security': 'Privacy & Security',
      'help_support': 'Help & Support',
    },
    'bn': {
      'welcome_to': 'স্বাগতম',
      'ruqyah_healing': 'রুকিয়াহ হিলিং',
      'tagline': 'দেহ, মন ও আত্মার সহানুভূতিশীল সেবা',
      'choose_language': 'আপনার ভাষা নির্বাচন করুন',
      'continue': 'এগিয়ে যান',
      'sign_in_account': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
      'create_account_title': 'অ্যাকাউন্ট তৈরি করুন',
      'email': 'ইমেইল',
      'phone': 'ফোন',
      'email_address': 'ইমেইল ঠিকানা',
      'password': 'পাসওয়ার্ড',
      'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'sign_in': 'সাইন ইন',
      'sign_up': 'সাইন আপ',
      'send_otp': 'ওটিপি পাঠান',
      'otp_code': 'ওটিপি কোড',
      'select_role': 'ভূমিকা নির্বাচন করুন',
      'user': 'ব্যবহারকারী',
      'raki': 'রাকী',
      'therapist': 'থেরাপিস্ট',
      'full_name': 'সম্পূর্ণ নাম',
      'or_continue_with': 'অথবা এটি দিয়ে চালিয়ে যান',
      'continue_google': 'গুগল দিয়ে চালিয়ে যান',
      'home': 'হোম',
      'services': 'সেবা',
      'bookings': 'বুকিং',
      'learn': 'শিখুন',
      'profile': 'প্রোফাইল',
      'settings': 'সেটিংস',
      'greeting': 'আসসালামু আলাইকুম,',
      'health_index': 'স্বাস্থ্য ইনডেক্স',
      'holistic_services': 'হোলিস্টিক সেবা',
      'prayer_times': 'আজকের নামাযের সময়',
      'my_appointments': 'আমার অ্যাপয়েন্টমেন্ট',
      'browse_category': 'ক্যাটাগরি অনুযায়ী দেখুন',
      'featured_courses': 'বিশেষ কোর্সসমূহ',
      'personal_info': 'ব্যক্তিগত তথ্য',
      'logout': 'লগআউট',
      'theme_mode': 'থিম মোড',
      'language': 'ভাষা',
      'good': 'ভালো',
      'overall_wellness': 'সামগ্রিক শারীরিক ও আত্মিক সুস্থতা',
      'next_appointment': 'পরবর্তী অ্যাপয়েন্টমেন্ট',
      'ruqyah': 'রুকিয়াহ',
      'hijama': 'হিজামা',
      'acupuncture': 'আকুপাংচার',
      'emergency': 'জরুরী সেবা',
      'preferences': 'পছন্দসমূহ',
      'text_size': 'টেক্সট সাইজ',
      'display': 'ডিসপ্লে',
      'reduce_motion': 'রিডিউস মোশন',
      'prayer_reminders': 'নামাযের রিমাইন্ডার',
      'audio_downloads': 'অডিও ডাউনলোড',
      'security_privacy': 'নিরাপত্তা ও গোপনীয়তা',
      'biometric_lock': 'বায়োমেট্রিক লক',
      'connected_devices': 'সংযুক্ত ডিভাইস',
      'health_connect': 'হেলথ কানেক্ট',
      'notification_settings': 'নোটিফিকেশন সেটিংস',
      'export_my_data': 'আমার ডাটা এক্সপোর্ট করুন',
      'delete_account': 'অ্যাকাউন্ট মুছে ফেলুন',
      'about_legal': 'সম্পর্কে ও আইনি তথ্য',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'terms_of_service': 'সেবার শর্তাবলী',
      'about_ruqyah': 'রুকিয়াহ হিলিং সম্পর্কে',
      'ai_symptom_guide': 'এআই উপসর্গ নির্দেশিকা',
      'ai_symptom_sub': 'তাত্ক্ষণিক ইসলামিক পরামর্শ ও দোআ পান',
      'ruqyah_title': 'রুকিয়াহ',
      'ruqyah_sub': 'সুরক্ষা ও আত্মিক প্রশান্তির জন্য কুরআনভিত্তিক চিকিৎসা।',
      'hijama_title': 'হিজামা',
      'hijama_sub': 'প্রাকৃতিক ডিটক্সিফিকেশন ও শারীরিক পুনরুদ্ধারের কাপিং থেরাপি।',
      'acupuncture_title': 'আকুপাংচার',
      'acupuncture_sub': 'শারীরিক ভারসাম্য ও শক্তি বজায় রাখার জন্য হোলিস্টিক চিকিৎসা।',
      'courses': 'কোর্সসমূহ',
      'learn_protection': 'সুরক্ষা শিখুন...',
      'store': 'স্টোর',
      'natural_remedies': 'প্রাকৃতিক প্রতিকার...',
      'patient_portal': 'প্যাশেন্ট পোর্টাল',
      'upcoming': 'আসন্ন',
      'completed': 'সম্পন্ন',
      'cancelled': 'বাতিল',
      'upcoming_sessions': 'আসন্ন সেশনসমূহ',
      'rescheduling_info': 'সেশনের ২৪ ঘণ্টা আগে বিনামূল্যে পুনর্নির্ধারণ বা বাতিল করা যাবে।',
      'add_to_calendar': 'ক্যালেন্ডারে যোগ করুন',
      'book_new_appointment': 'নতুন অ্যাপয়েন্টমেন্ট বুক করুন',
      'learning': 'শিক্ষা কেন্দ্র',
      'learning_sub': 'জ্ঞানে বৃদ্ধি পান, নিষ্ঠার সাথে সেবা করুন।',
      'continue_learning': 'পড়া চালিয়ে যান',
      'view_all': 'সব দেখুন',
      'sessions_completed': 'সেশন সম্পন্ন',
      'health_index_label': 'স্বাস্থ্য ইনডেক্স',
      'days_active': 'দিন সক্রিয়',
      'streak_tracker': 'স্ট্রিক ট্র্যাকার',
      'subscription_plans': 'সাবস্ক্রিপশন প্ল্যান',
      'payment_methods': 'পেমেন্ট মেথড',
      'notifications': 'নোটিফিকেশন',
      'privacy_security': 'প্রাইভেসি ও সিকিউরিটি',
      'help_support': 'হেল্প ও সাপোর্ট',
    },
    'ar': {
      'welcome_to': 'مرحباً بكم في',
      'ruqyah_healing': 'الرقية الشرعية',
      'tagline': 'رعاية شفيقة للجسد والعقل والروح',
      'choose_language': 'اختر لغتك',
      'continue': 'متابعة',
      'sign_in_account': 'تسجيل الدخول إلى حسابك',
      'create_account_title': 'إنشاء حساب جديد',
      'email': 'البريد',
      'phone': 'الهاتف',
      'email_address': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'send_otp': 'إرسال الرمز',
      'otp_code': 'رمز التحقق',
      'select_role': 'اختر الصفة',
      'user': 'مستخدم',
      'raki': 'راقي',
      'therapist': 'معالج',
      'full_name': 'الاسم الكامل',
      'or_continue_with': 'أو المتابعة باستخدام',
      'continue_google': 'المتابعة بـ Google',
      'home': 'الرئيسية',
      'services': 'الخدمات',
      'bookings': 'الحجوزات',
      'learn': 'تعلم',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'greeting': 'السلام عليكم،',
      'health_index': 'مؤشر الصحة',
      'holistic_services': 'الخدمات الشاملة',
      'prayer_times': 'مواقيت الصلاة اليوم',
      'my_appointments': 'مواعيدي',
      'browse_category': 'التصفح حسب الفئة',
      'featured_courses': 'الدورات المميزة',
      'personal_info': 'المعلومات الشخصية',
      'logout': 'تسجيل الخروج',
      'theme_mode': 'وضع المظهر',
      'language': 'اللغة',
      'good': 'جيد',
      'overall_wellness': 'العافية الجسدية والروحية الشاملة',
      'next_appointment': 'الموعد القادم',
      'ruqyah': 'الرقية',
      'hijama': 'الحجامة',
      'acupuncture': 'الوخز بالإبر',
      'emergency': 'الطوارئ',
      'preferences': 'التفضيلات',
      'text_size': 'حجم النص',
      'display': 'العرض',
      'reduce_motion': 'تقليل الحركة',
      'prayer_reminders': 'تنبيهات الصلاة',
      'audio_downloads': 'تنزيلات الصوت',
      'security_privacy': 'الأمان والخصوصية',
      'biometric_lock': 'القفل البيومتري',
      'connected_devices': 'الأجهزة المتصلة',
      'health_connect': 'الربط الصحي',
      'notification_settings': 'إعدادات الإشعارات',
      'export_my_data': 'تصدير بياناتي',
      'delete_account': 'حذف الحساب',
      'about_legal': 'حول والقانونية',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_of_service': 'شروط الخدمة',
      'about_ruqyah': 'حول الرقية الشرعية',
      'ai_symptom_guide': 'دليل الأعراض بالذكاء الاصطناعي',
      'ai_symptom_sub': 'احصل على إرشاد إسلامي وأدعية فورية',
      'ruqyah_title': 'الرقية الشرعية',
      'ruqyah_sub': 'علاج قرآني للحماية والراحة من الضيق الروحي.',
      'hijama_title': 'الحجامة',
      'hijama_sub': 'علاج بالحجامة لتنقية الجسم واستعادة العافية.',
      'acupuncture_title': 'الوخز بالإبر',
      'acupuncture_sub': 'ممارسات علاجية شاملة للحفاظ على التوازن والتطبيش.',
      'courses': 'الدورات',
      'learn_protection': 'تعلم الحماية...',
      'store': 'المتجر',
      'natural_remedies': 'العلاجات الطبيعية...',
      'patient_portal': 'بوابة المريض',
      'upcoming': 'القادمة',
      'completed': 'المكتملة',
      'cancelled': 'الملغاة',
      'upcoming_sessions': 'الجلسات القادمة',
      'rescheduling_info': 'يُسمح بإعادة الجدولة أو الإلغاء مجانًا قبل 24 ساعة من الجلسة.',
      'add_to_calendar': 'إضافة المواعيد للتقويم',
      'book_new_appointment': 'حجز موعد جديد',
      'learning': 'التعليم',
      'learning_sub': 'تطوير المعرفة والخدمة بإخلاص.',
      'continue_learning': 'متابعة التعلم',
      'view_all': 'عرض الكل',
      'sessions_completed': 'الجلسات المكتملة',
      'health_index_label': 'مؤشر الصحة',
      'days_active': 'أيام النشاط',
      'streak_tracker': 'متابع الاستمرارية',
      'subscription_plans': 'خطط الاشتراك',
      'payment_methods': 'طرق الدفع',
      'notifications': 'الإشعارات',
      'privacy_security': 'الخصوصية والأمان',
      'help_support': 'المساعدة والدعم',
    },
    'ur': {
      'welcome_to': 'خوش آمدید',
      'ruqyah_healing': 'رقیہ ہیلنگ',
      'tagline': 'جسم، ذہن اور روح کی دیکھ بھال',
      'choose_language': 'اپنی زبان منتخب کریں',
      'continue': 'جاری رکھیں',
      'sign_in_account': 'اپنے اکاؤنٹ میں سائن ان کریں',
      'create_account_title': 'نیا اکاؤنٹ بنائیں',
      'email': 'ای میل',
      'phone': 'فون',
      'email_address': 'ای میل ایڈریس',
      'password': 'پاس ورڈ',
      'confirm_password': 'پاس ورڈ کی تصدیق کریں',
      'forgot_password': 'پاس ورڈ بھول گئے؟',
      'sign_in': 'سائن ان',
      'sign_up': 'سائن اپ',
      'send_otp': 'او ٹی پی بھیجیں',
      'otp_code': 'او ٹی پی کوڈ',
      'select_role': 'کردار منتخب کریں',
      'user': 'صارف',
      'raki': 'راقی',
      'therapist': 'معالج',
      'full_name': 'مکمل نام',
      'or_continue_with': 'یا اس کے ساتھ جاری رکھیں',
      'continue_google': 'گوگل کے ساتھ جاری رکھیں',
      'home': 'ہوم',
      'services': 'خدمات',
      'bookings': 'بکنگز',
      'learn': 'سیکھیں',
      'profile': 'پروفائل',
      'settings': 'سیٹنگز',
      'greeting': 'السلام علیکم،',
      'health_index': 'ہیلتھ انڈیکس',
      'holistic_services': 'ہولسٹک سروسز',
      'prayer_times': 'آج کے اوقاتِ نماز',
      'my_appointments': 'میری اپائنٹمنٹس',
      'browse_category': 'زمرہ جات کے لحاظ سے دیکھئے',
      'featured_courses': 'نمایاں کورسز',
      'personal_info': 'ذاتی معلومات',
      'logout': 'لاگ آؤٹ',
      'theme_mode': 'تھیم موڈ',
      'language': 'زبان',
      'good': 'بہتر',
      'overall_wellness': 'مجموعی جسمانی اور روحانی صحت',
      'next_appointment': 'اگلی اپائنٹمنٹ',
      'ruqyah': 'رقیہ',
      'hijama': 'حجامہ',
      'acupuncture': 'ایکیوپنکچر',
      'emergency': 'ہنگامی',
      'preferences': 'ترجیحات',
      'text_size': 'ٹیکسٹ سائز',
      'display': 'ڈسپلے',
      'reduce_motion': 'ریڈیوس موشن',
      'prayer_reminders': 'نماز کی یاد دہانی',
      'audio_downloads': 'آڈیو ڈاؤن لوڈز',
      'security_privacy': 'سیکیورٹی اور پرائیویسی',
      'biometric_lock': 'بایومیٹرک لاک',
      'connected_devices': 'منسلک ڈیوائسز',
      'health_connect': 'ہیلتھ کنیکٹ',
      'notification_settings': 'نوٹیفکیشن سیٹنگز',
      'export_my_data': 'ڈیٹا ایکسپورٹ کریں',
      'delete_account': 'اکاؤنٹ ختم کریں',
      'about_legal': 'معلومات اور قانونی',
      'privacy_policy': 'پرائیویسی پالیسی',
      'terms_of_service': 'سروس کی شرائط',
      'about_ruqyah': 'رقیہ ہیلنگ کے بارے میں',
      'ai_symptom_guide': 'اے آئی علامت گائیڈ',
      'ai_symptom_sub': 'فوری اسلامی رہنمائی اور دعائیں حاصل کریں',
      'ruqyah_title': 'رقیہ',
      'ruqyah_sub': 'حفاظت اور روحانی سکون کے لیے قرآنی علاج۔',
      'hijama_title': 'حجامہ',
      'hijama_sub': 'جسم کی صفائی اور بحالی کے لیے کپنگ تھراپی۔',
      'acupuncture_title': 'ایکیوپنکچر',
      'acupuncture_sub': 'جسمانی توازن برقرار رکھنے کے لیے شفا بخش علاج۔',
      'courses': 'کورسز',
      'learn_protection': 'حفاظت سیکھیں...',
      'store': 'اسٹور',
      'natural_remedies': 'قدرتی علاج...',
      'patient_portal': 'پیشنٹ پورٹل',
      'upcoming': 'آنے والی',
      'completed': 'مکمل',
      'cancelled': 'منسوخ',
      'upcoming_sessions': 'آنے والے سیشنز',
      'rescheduling_info': 'سیشن سے 24 گھنٹے قبل مفت تاریخ کی تبدیلی یا منسوخی ممکن ہے۔',
      'add_to_calendar': 'کیلنڈر میں شامل کریں',
      'book_new_appointment': 'نئی اپائنٹمنٹ بک کریں',
      'learning': 'سیکھنے کا مرکز',
      'learning_sub': 'علم میں اضافہ کریں، اخلاص کے ساتھ خدمت کریں۔',
      'continue_learning': 'سیکھنا جاری رکھیں',
      'view_all': 'سب دیکھیں',
      'sessions_completed': 'مکمل سیشنز',
      'health_index_label': 'ہیلتھ انڈیکس',
      'days_active': 'فعال ایام',
      'streak_tracker': 'اسٹریک ٹریکر',
      'subscription_plans': 'سبسکرپشن پلانز',
      'payment_methods': 'ادائیگی کے طریقے',
      'notifications': 'نوٹیفکیشنز',
      'privacy_security': 'پرائیویسی اور سیکیورٹی',
      'help_support': 'مدد اور تعاون',
    },
  };

  static String tr(BuildContext context, String key) {
    final lang = currentLocaleNotifier.value.languageCode;
    return _localizedValues[lang]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

extension LocalizationContext on BuildContext {
  String tr(String key) => AppLocalizations.tr(this, key);
}
