// File generated by FlutterFire CLI or configured manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp`.
///
/// Replace placeholders with your Firebase project credentials from Firebase Console,
/// or run `flutterfire configure` to generate automatically.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwab1Ik-uqKIzmfrlIgyIqnspkYtI1HpY',
    appId: '1:968913433241:web:6aed41e4e81a7846a2fe08',
    messagingSenderId: '968913433241',
    projectId: 'ruqyah-healing-f1b46',
    authDomain: 'ruqyah-healing-f1b46.firebaseapp.com',
    databaseURL: 'https://ruqyah-healing-f1b46-default-rtdb.firebaseio.com',
    storageBucket: 'ruqyah-healing-f1b46.firebasestorage.app',
    measurementId: 'G-2ZS2JQGNX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5lQY4qRTfo_A98DBRRUL737Qwr5eHAw',
    appId: '1:968913433241:android:f960285f701be8a2a2fe08',
    messagingSenderId: '968913433241',
    projectId: 'ruqyah-healing-f1b46',
    databaseURL: 'https://ruqyah-healing-f1b46-default-rtdb.firebaseio.com',
    storageBucket: 'ruqyah-healing-f1b46.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUhb4YW81h-5b1-6SLpzb3AaBSo3RtdE',
    appId: '1:968913433241:ios:bee3e04085e7cb2ca2fe08',
    messagingSenderId: '968913433241',
    projectId: 'ruqyah-healing-f1b46',
    databaseURL: 'https://ruqyah-healing-f1b46-default-rtdb.firebaseio.com',
    storageBucket: 'ruqyah-healing-f1b46.firebasestorage.app',
    iosClientId: '968913433241-rfo96nqtrm1brrbcnmesngcnkcltim1g.apps.googleusercontent.com',
    iosBundleId: 'com.vertexhand.ruqyahhealing',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbUhb4YW81h-5b1-6SLpzb3AaBSo3RtdE',
    appId: '1:968913433241:ios:bee3e04085e7cb2ca2fe08',
    messagingSenderId: '968913433241',
    projectId: 'ruqyah-healing-f1b46',
    databaseURL: 'https://ruqyah-healing-f1b46-default-rtdb.firebaseio.com',
    storageBucket: 'ruqyah-healing-f1b46.firebasestorage.app',
    iosClientId: '968913433241-rfo96nqtrm1brrbcnmesngcnkcltim1g.apps.googleusercontent.com',
    iosBundleId: 'com.vertexhand.ruqyahhealing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwab1Ik-uqKIzmfrlIgyIqnspkYtI1HpY',
    appId: '1:968913433241:web:d8c2a7fa0bf0e9d5a2fe08',
    messagingSenderId: '968913433241',
    projectId: 'ruqyah-healing-f1b46',
    authDomain: 'ruqyah-healing-f1b46.firebaseapp.com',
    databaseURL: 'https://ruqyah-healing-f1b46-default-rtdb.firebaseio.com',
    storageBucket: 'ruqyah-healing-f1b46.firebasestorage.app',
    measurementId: 'G-PKL4P9MD0X',
  );
}
